volumes:
  local_postgres_data: {}

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "8000:8000"
#    command: bash -c "python wait_for_postgres.py && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
  
  postgres:
    image: postgres:16.4-bookworm
    volumes:
    - local_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4.1
    ports:
      - "6379:6379"