# Generated by Django 5.1.2 on 2024-11-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('author', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('isbn', models.TextField(max_length=13, primary_key=True, serialize=False)),
                ('publication_date', models.DateField()),
                ('title', models.TextField()),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
