# Generated by Django 5.1.2 on 2024-11-05 20:45

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.TextField(
                max_length=13,
                primary_key=True,
                serialize=False,
                validators=[books.models.somewhat_validate_isbn],
            ),
        ),
    ]
