# Generated by Django 5.1.2 on 2024-11-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['created_at'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['created_at'], name='books_book_created_572b47_idx'),
        ),
    ]
